"use client";

import { useMemo } from "react";
import { useData } from "@/context/data-context";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import { formatIDR } from "@/lib/analytics";
import { Users, DollarSign, TrendingUp, Percent } from "lucide-react";
import { KOLProfileDialog } from "@/components/kols/kol-profile-dialog";

export default function AffiliatesPage() {
    const { campaigns, kols } = useData();

    // Get all AFFILIATE deliverables across all campaigns
    const affiliateData = useMemo(() => {
        const results: {
            kolId: string;
            kolName: string;
            campaignId: string;
            campaignName: string;
            commissionRate: number;
            revenue: number;
            commissionEarned: number;
            roas: number;
            kol: typeof kols[0] | undefined;
        }[] = [];

        campaigns.forEach(campaign => {
            campaign.deliverables
                .filter(d => d.collaborationType === 'AFFILIATE')
                .forEach(del => {
                    const kol = kols.find(k => k.id === del.kolId);
                    const rate = del.commissionRate || 0;
                    const revenue = del.salesGenerated || 0;
                    const commission = revenue * (rate / 100);
                    const roas = commission > 0 ? revenue / commission : 0;

                    results.push({
                        kolId: del.kolId,
                        kolName: kol?.name || 'Unknown',
                        campaignId: campaign.id,
                        campaignName: campaign.name,
                        commissionRate: rate,
                        revenue,
                        commissionEarned: commission,
                        roas,
                        kol
                    });
                });
        });

        return results;
    }, [campaigns, kols]);

    // Summary calculations
    const summary = useMemo(() => {
        const totalAffiliates = new Set(affiliateData.map(d => d.kolId)).size;
        const totalRevenue = affiliateData.reduce((sum, d) => sum + d.revenue, 0);
        const totalCommission = affiliateData.reduce((sum, d) => sum + d.commissionEarned, 0);
        const avgRoas = totalCommission > 0 ? totalRevenue / totalCommission : 0;

        return { totalAffiliates, totalRevenue, totalCommission, avgRoas };
    }, [affiliateData]);

    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div>
                <h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
                    Affiliate Dashboard
                </h1>
                <p className="text-slate-500 dark:text-slate-400 mt-1">
                    Track performance of all affiliate (commission-based) collaborations.
                </p>
            </div>

            {/* Summary Cards */}
            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                <Card className="border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Affiliates</CardTitle>
                        <Users className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{summary.totalAffiliates}</div>
                        <p className="text-xs text-muted-foreground">Active affiliate KOLs</p>
                    </CardContent>
                </Card>

                <Card className="border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
                        <DollarSign className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{formatIDR(summary.totalRevenue)}</div>
                        <p className="text-xs text-muted-foreground">Generated by affiliates</p>
                    </CardContent>
                </Card>

                <Card className="border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Commission Paid</CardTitle>
                        <Percent className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{formatIDR(summary.totalCommission)}</div>
                        <p className="text-xs text-muted-foreground">Auto-settled commissions</p>
                    </CardContent>
                </Card>

                <Card className="border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">Average ROAS</CardTitle>
                        <TrendingUp className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">{summary.avgRoas.toFixed(2)}x</div>
                        <p className="text-xs text-muted-foreground">Return on commission spend</p>
                    </CardContent>
                </Card>
            </div>

            {/* Affiliate Table */}
            <Card className="border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]">
                <CardHeader>
                    <CardTitle>Affiliate Performance</CardTitle>
                </CardHeader>
                <CardContent>
                    {affiliateData.length === 0 ? (
                        <div className="text-center py-12 text-muted-foreground">
                            <Users className="h-12 w-12 mx-auto mb-4 opacity-50" />
                            <p className="text-lg font-medium">No affiliate collaborations yet</p>
                            <p className="text-sm">Add KOLs with &quot;AFFILIATE&quot; type to see them here.</p>
                        </div>
                    ) : (
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>KOL Name</TableHead>
                                    <TableHead>Campaign</TableHead>
                                    <TableHead className="text-center">Commission %</TableHead>
                                    <TableHead className="text-right">Revenue</TableHead>
                                    <TableHead className="text-right">Commission Earned</TableHead>
                                    <TableHead className="text-center">ROAS</TableHead>
                                    <TableHead className="text-center">Status</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {affiliateData.map((item, index) => (
                                    <TableRow key={`${item.kolId}-${item.campaignId}-${index}`}>
                                        <TableCell className="font-medium">
                                            {item.kol ? (
                                                <KOLProfileDialog kol={item.kol}>
                                                    <span className="font-bold hover:underline cursor-pointer">{item.kolName}</span>
                                                </KOLProfileDialog>
                                            ) : (
                                                <span>{item.kolName}</span>
                                            )}
                                        </TableCell>
                                        <TableCell>{item.campaignName}</TableCell>
                                        <TableCell className="text-center font-medium">{item.commissionRate}%</TableCell>
                                        <TableCell className="text-right">{formatIDR(item.revenue)}</TableCell>
                                        <TableCell className="text-right font-medium text-green-600">{formatIDR(item.commissionEarned)}</TableCell>
                                        <TableCell className="text-center">
                                            <Badge variant="outline" className={item.roas >= 2 ? 'bg-green-100 text-green-700' : 'bg-yellow-100 text-yellow-700'}>
                                                {item.roas.toFixed(2)}x
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-center">
                                            <Badge className="bg-green-100 text-green-700 border border-green-300">
                                                Auto-Settled
                                            </Badge>
                                        </TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                    )}
                </CardContent>
            </Card>
        </div>
    );
}
